kind: pipeline
name: Sync

steps:
  - name: Sync Github
    image: ghcr.io/virzz/drone-git-sync:latest
    settings:
      remote: "ssh://git@github.com/ctfhub-team/meta.git"
      force: true
      ssh_key:
        from_secret: SYNC_GITHUB_KEY
